version: '3.3'
services:
  # Run a mysql database in docker container
  # Use it with command 'docker-compose up bank-db'
  bank-db:
    image: "mysql:5.7.24"
    container_name: "bank-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"